server:
 port: 9999
spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      routes:
       - id: USER-SERVICE
         uri: lb://USER-SERVICE
         predicates:
          - Path=/lbusers/**
        
       - id: BOOKS-SERVICE
         uri: lb://BOOKS-SERVICE
         predicates:
          - Path=/books/**
         
  
eureka:
  client:
   register-with-eureka: true
   serivce-url: 
    defaultZone: http://localhost:8761/eureka
